# Generated by Django 3.2.7 on 2021-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
